using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CsvHelper.Configuration;

namespace PPI.Hogan.Service.Utility
{
    public sealed class Hogan_File_Map : CsvClassMap<PPI.Core.Domain.Entities.Manual_Hogan_Import>
    {
        [Obsolete]
        public override void CreateMap()
        {

            Map(m => m.ClientID);
            Map(m => m.ClientName);
            Map(m => m.Hogan_User_ID).Index(3);
            Map(m => m.First_Name).Index(4);
            Map(m => m.Last_Name).Index(5);
            Map(m => m.Gender);
            Map(m => m.HPIDate);
            Map(m => m.HDSDate);
            Map(m => m.MVPIDate);
            Map(m => m.Valid).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Empathy).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NotAnxious).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NoGuilt).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Calmness).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.EvenTempered).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NoSomaticComplaint).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Trusting).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.GoodAttachment).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Competitive).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.SelfConfidence).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NoDepression).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Leadership).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Identity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NoSocialAnxiety).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.LikesParties).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.LikesCrowds).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.ExperienceSeeking).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Exhibitionistic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Entertaining).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.EasyToLiveWith).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Sensitive).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Caring).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.LikesPeople).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NoHostility).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Moralistic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Mastery).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Virtuous).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NotAutonomous).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.NotSpontaneous).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.ImpulseControl).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.AvoidsTrouble).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.ScienceAbility).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Curiosity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.ThrillSeeking).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.IntellectualGames).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.GeneratesIdeas).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Culture).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Education).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.MathAbility).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.GoodMemory).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.Reading).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RValidity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAdjustment).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAmbition).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSociability).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RInterpersonalSensitivity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RPrudence).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RInquisitive).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RLearningApproach).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RServiceOrientation).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RStressTolerance).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RReliability).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RClericalPotential).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSalesPotential).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RManagerialPotential).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PValidity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PAdjustment).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PAmbition).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PSociability).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PInterpersonalSensitivity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PPrudence).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PInquisitive).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PLearningApproach).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PServiceOrientation).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PStressTolerance).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PReliability).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PClericalPotential).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PSalesPotential).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PManagerialPotential).TypeConverterOption(System.Globalization.NumberStyles.Integer);

            Map(m => m.RExcitable).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSkeptical).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RCautious).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RReserved).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RLeisurely).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RBold).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RMischievous).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RColorful).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RImaginative).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RDiligent).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RDutiful).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RUnlikeness).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PExcitable).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PSkeptical).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PCautious).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PReserved).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PLeisurely).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PBold).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PMischievous).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PColorful).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PImaginative).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PDiligent).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PDutiful).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PUnlikeness).TypeConverterOption(System.Globalization.NumberStyles.Integer);

            Map(m => m.RAesthetic_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAesthetic_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAesthetic_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAesthetic_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAesthetic_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAffiliation_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAffiliation_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAffiliation_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAffiliation_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAffiliation_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAltruistic_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAltruistic_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAltruistic_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAltruistic_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAltruistic_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RCommercial_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RCommercial_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RCommercial_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RCommercial_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RCommercial_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RHedonistic_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RHedonistic_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RHedonistic_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RHedonistic_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RHedonistic_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RPower_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RPower_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RPower_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RPower_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RPower_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RRecognition_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RRecognition_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RRecognition_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RRecognition_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RRecognition_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RScientific_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RScientific_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RScientific_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RScientific_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RScientific_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSecurity_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSecurity_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSecurity_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSecurity_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSecurity_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RTradition_Lifestyles).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RTradition_Beliefs).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RTradition_Occupational_Prferences).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RTradition_Aversions).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RTradition_Preferred_Associates).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAesthetic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAffiliation).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RAltruistic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RCommercial).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RHedonistic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RPower).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RRecognition).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RScientific).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RSecurity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.RTradition).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PAesthetic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PAffiliation).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PAltruistic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PCommercial).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PHedonistic).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PPower).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PRecognition).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PScientific).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PSecurity).TypeConverterOption(System.Globalization.NumberStyles.Integer);
            Map(m => m.PTradition).TypeConverterOption(System.Globalization.NumberStyles.Integer);
        }
    }
}
