//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentResponseQuestionOption
    {
        public int Id { get; set; }
        public int AssessmentResponseId { get; set; }
        public int AssessmentQuestionId { get; set; }
        public int AssessmentQuestionOptionId { get; set; }
    
        public virtual AssessmentQuestion AssessmentQuestion { get; set; }
        public virtual AssessmentQuestionOption AssessmentQuestionOption { get; set; }
        public virtual AssessmentResponse AssessmentResponse { get; set; }
    }
}
