//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQuestionOption
    {
        public AssessmentQuestionOption()
        {
            this.AssessmentResponseQuestionOption = new HashSet<AssessmentResponseQuestionOption>();
        }
    
        public int Id { get; set; }
        public string Option { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<AssessmentResponseQuestionOption> AssessmentResponseQuestionOption { get; set; }
    }
}
