//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentResponse
    {
        public AssessmentResponse()
        {
            this.AssessmentResponseQuestionOption = new HashSet<AssessmentResponseQuestionOption>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<AssessmentResponseQuestionOption> AssessmentResponseQuestionOption { get; set; }
    }
}
