//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailStatus
    {
        public EmailStatus()
        {
            this.PersonEmail = new HashSet<PersonEmail>();
        }
    
        public int Id { get; set; }
        public int NameResxId { get; set; }
    
        public virtual Resx Resx { get; set; }
        public virtual ICollection<PersonEmail> PersonEmail { get; set; }
    }
}
