//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.PersonEmail = new HashSet<PersonEmail>();
            this.ScheduledEmail = new HashSet<ScheduledEmail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> EmailTypeId { get; set; }
        public string DefaultFrom { get; set; }
        public string Subject { get; set; }
        public string Introduction { get; set; }
        public string Closing { get; set; }
    
        public virtual EmailType EmailType { get; set; }
        public virtual ICollection<PersonEmail> PersonEmail { get; set; }
        public virtual ICollection<ScheduledEmail> ScheduledEmail { get; set; }
        public virtual Event Event { get; set; }
    }
}
