//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPracticeReport
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public int PracticeReportId { get; set; }
        public Nullable<int> ReportTitleResxId { get; set; }
        public byte[] DefaultLogo { get; set; }
        public string DefaultLogoMimeType { get; set; }
        public byte[] DefaultBackground { get; set; }
        public string DefaultBackgroundMimeType { get; set; }
        public string DefaultColor { get; set; }
        public Nullable<int> IntroductionResxId { get; set; }
        public Nullable<int> IntroductionTwoResxId { get; set; }
        public Nullable<int> IntroductionThreeResxId { get; set; }
    
        public virtual Resx Resx { get; set; }
        public virtual Resx Resx1 { get; set; }
        public virtual Resx Resx2 { get; set; }
        public virtual PracticeReport PracticeReport { get; set; }
        public virtual Resx Resx3 { get; set; }
        public virtual Event Event { get; set; }
    }
}
