//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoganField
    {
        public HoganField()
        {
            this.PracticeCategoryParagraphs = new HashSet<PracticeCategoryParagraphs>();
            this.PracticeCategoryScale = new HashSet<PracticeCategoryScale>();
            this.PracticeScale = new HashSet<PracticeScale>();
        }
    
        public int Id { get; set; }
        public string FieldName { get; set; }
        public string LabelName { get; set; }
        public Nullable<int> StandardOrder { get; set; }
        public Nullable<int> DefinitionTextResxId { get; set; }
        public Nullable<int> BlurbTextResxId { get; set; }
        public string HoganCategory { get; set; }
    
        public virtual Resx Resx { get; set; }
        public virtual Resx Resx1 { get; set; }
        public virtual ICollection<PracticeCategoryParagraphs> PracticeCategoryParagraphs { get; set; }
        public virtual ICollection<PracticeCategoryScale> PracticeCategoryScale { get; set; }
        public virtual ICollection<PracticeScale> PracticeScale { get; set; }
    }
}
