//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoganUserInfo
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string GroupName { get; set; }
        public int ProgramId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public bool Used { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
