//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OESSetup
    {
        public OESSetup()
        {
            this.OESPracticeReport = new HashSet<OESPracticeReport>();
            this.OESSchedule = new HashSet<OESSchedule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int EventTypeId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string AspNetUserId { get; set; }
        public string DefaultEmail { get; set; }
        public Nullable<bool> Billable { get; set; }
        public Nullable<int> NotBillableReasonId { get; set; }
        public string BDOpportunity { get; set; }
        public Nullable<int> VGSpecialtyId { get; set; }
        public Nullable<int> NoOfParticipants { get; set; }
        public Nullable<bool> CompositeRequired { get; set; }
        public Nullable<bool> JETRequired { get; set; }
        public Nullable<int> SurveyTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int OrderStatusId { get; set; }
    
        public virtual AspNetUser AspNetUsers { get; set; }
        public virtual EventNotBillableReason EventNotBillableReason { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual EventVGSpecialty EventVGSpecialty { get; set; }
        public virtual ICollection<OESPracticeReport> OESPracticeReport { get; set; }
        public virtual ICollection<OESSchedule> OESSchedule { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Program Program { get; set; }
        public virtual Site Site { get; set; }
        public virtual SurveyType SurveyType { get; set; }
    }
}
