//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderForm
    {
        public OrderForm()
        {
            this.OrderFormPracticeReports = new HashSet<OrderFormPracticeReport>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Site { get; set; }
        public int ProgramId { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public Nullable<bool> Billable { get; set; }
        public string SalesType { get; set; }
        public int EventTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<int> Placement { get; set; }
        public string Info { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Program Program { get; set; }
        public virtual ICollection<OrderFormPracticeReport> OrderFormPracticeReports { get; set; }
    }
}
