//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Site = new HashSet<Site>();
            this.OESSetup = new HashSet<OESSetup>();
        }
    
        public int Id { get; set; }
        public string OrganizationName { get; set; }
    
        public virtual ICollection<Site> Site { get; set; }
        public virtual ICollection<OESSetup> OESSetup { get; set; }
    }
}
