//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEmail
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int EmailId { get; set; }
        public Nullable<int> EmailStatusId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string EmailBody { get; set; }
        public int RetryCount { get; set; }
        public string ErrorMessage { get; set; }
        public string Origin { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual EmailStatus EmailStatus { get; set; }
        public virtual Person Person { get; set; }
    }
}
