//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPracticeReport
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int PracticeReportId { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public string AspNetUsersId { get; set; }
        public Nullable<int> EventId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Person Person { get; set; }
        public virtual PracticeReport PracticeReport { get; set; }
        public virtual Event Event { get; set; }
    }
}
