//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonEmails = new HashSet<PersonEmail>();
            this.PersonEvents = new HashSet<PersonEvent>();
            this.PersonPracticeReport = new HashSet<PersonPracticeReport>();
            this.ScheduledEmailPersons = new HashSet<ScheduledEmailPerson>();
            this.vDashboard = new HashSet<vDashboard>();
            this.vPersonBySite = new HashSet<vPersonBySite>();
            this.AssessmentResponse = new HashSet<AssessmentResponse>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Title { get; set; }
        public string AAMCNumber { get; set; }
        public string PrimaryEmail { get; set; }
        public string Hogan_Id { get; set; }
        public string Hogan_Password { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string J3P_Id { get; set; }
    
        public virtual ICollection<PersonEmail> PersonEmails { get; set; }
        public virtual ICollection<PersonEvent> PersonEvents { get; set; }
        public virtual ICollection<PersonPracticeReport> PersonPracticeReport { get; set; }
        public virtual ICollection<ScheduledEmailPerson> ScheduledEmailPersons { get; set; }
        public virtual ICollection<vDashboard> vDashboard { get; set; }
        public virtual ICollection<vPersonBySite> vPersonBySite { get; set; }
        public virtual ICollection<AssessmentResponse> AssessmentResponse { get; set; }
    }
}
