//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeCategoryScale
    {
        public int Id { get; set; }
        public int ProgramId { get; set; }
        public int PracticeCategoryId { get; set; }
        public int HoganFieldId { get; set; }
        public int LowerBound { get; set; }
        public int UpperBound { get; set; }
    
        public virtual HoganField HoganField { get; set; }
        public virtual PracticeCategory PracticeCategory { get; set; }
        public virtual Program Program { get; set; }
    }
}
