//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeCategory
    {
        public PracticeCategory()
        {
            this.PracticeCategoryParagraphs = new HashSet<PracticeCategoryParagraphs>();
            this.PracticeCategoryScale = new HashSet<PracticeCategoryScale>();
            this.PracticeScale = new HashSet<PracticeScale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PracticeGroup { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual ICollection<PracticeCategoryParagraphs> PracticeCategoryParagraphs { get; set; }
        public virtual ICollection<PracticeCategoryScale> PracticeCategoryScale { get; set; }
        public virtual ICollection<PracticeScale> PracticeScale { get; set; }
    }
}
