//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeText
    {
        public PracticeText()
        {
            this.PracticeScaleReport = new HashSet<PracticeScaleReport>();
            this.PracticeScaleReport1 = new HashSet<PracticeScaleReport>();
            this.PracticeTextChildren = new HashSet<PracticeText>();
            this.PracticeTextOptionsAlternative = new HashSet<PracticeTextOption>();
            this.PracticeTextOptions = new HashSet<PracticeTextOption>();
        }
    
        public int Id { get; set; }
        public int TextResxId { get; set; }
        public string Text { get; set; }
        public Nullable<bool> IsIntroduction { get; set; }
        public Nullable<int> ParentPracticeTextId { get; set; }
    
        public virtual ICollection<PracticeScaleReport> PracticeScaleReport { get; set; }
        public virtual ICollection<PracticeScaleReport> PracticeScaleReport1 { get; set; }
        public virtual ICollection<PracticeText> PracticeTextChildren { get; set; }
        public virtual PracticeText PracticeTextPartent { get; set; }
        public virtual Resx TextResx { get; set; }
        public virtual ICollection<PracticeTextOption> PracticeTextOptionsAlternative { get; set; }
        public virtual ICollection<PracticeTextOption> PracticeTextOptions { get; set; }
    }
}
