//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeScaleReport
    {
        public int Id { get; set; }
        public int PracticeScaleId { get; set; }
        public int PracticeReportId { get; set; }
        public int Order { get; set; }
        public Nullable<int> SubOrder { get; set; }
        public int PracticeTextId { get; set; }
        public Nullable<int> InterviewPracticeTextId { get; set; }
    
        public virtual PracticeReport PracticeReport { get; set; }
        public virtual PracticeScale PracticeScale { get; set; }
        public virtual PracticeText PracticeText { get; set; }
        public virtual PracticeText PracticeText1 { get; set; }
    }
}
