//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramSite
    {
        public ProgramSite()
        {
            this.ProgramSiteHoganMVPIs = new HashSet<ProgramSiteHoganMVPI>();
            this.Event = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int ProgramId { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual ICollection<ProgramSiteHoganMVPI> ProgramSiteHoganMVPIs { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
}
