//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramSiteEvent
    {
        public ProgramSiteEvent()
        {
            this.PersonProgramSiteEvents = new HashSet<PersonProgramSiteEvent>();
        }
    
        public int Id { get; set; }
        public int ProgramSitesId { get; set; }
        public int EventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<PersonProgramSiteEvent> PersonProgramSiteEvents { get; set; }
        public virtual ProgramSite ProgramSite { get; set; }
    }
}
