//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resx
    {
        public Resx()
        {
            this.EmailStatus = new HashSet<EmailStatus>();
            this.EmailType = new HashSet<EmailType>();
            this.EventPracticeReport = new HashSet<EventPracticeReport>();
            this.EventPracticeReport1 = new HashSet<EventPracticeReport>();
            this.EventPracticeReport2 = new HashSet<EventPracticeReport>();
            this.EventPracticeReport3 = new HashSet<EventPracticeReport>();
            this.EventStatus = new HashSet<EventStatus>();
            this.EventType = new HashSet<EventType>();
            this.HoganField = new HashSet<HoganField>();
            this.HoganField1 = new HashSet<HoganField>();
            this.PracticeReport = new HashSet<PracticeReport>();
            this.PracticeReport1 = new HashSet<PracticeReport>();
            this.PracticeReport2 = new HashSet<PracticeReport>();
            this.PracticeReport3 = new HashSet<PracticeReport>();
            this.PracticeText = new HashSet<PracticeText>();
            this.ResxValues = new HashSet<ResxValue>();
        }
    
        public int Id { get; set; }
        public string DataColumnDescription { get; set; }
        public string DataColumnName { get; set; }
    
        public virtual ICollection<EmailStatus> EmailStatus { get; set; }
        public virtual ICollection<EmailType> EmailType { get; set; }
        public virtual ICollection<EventPracticeReport> EventPracticeReport { get; set; }
        public virtual ICollection<EventPracticeReport> EventPracticeReport1 { get; set; }
        public virtual ICollection<EventPracticeReport> EventPracticeReport2 { get; set; }
        public virtual ICollection<EventPracticeReport> EventPracticeReport3 { get; set; }
        public virtual ICollection<EventStatus> EventStatus { get; set; }
        public virtual ICollection<EventType> EventType { get; set; }
        public virtual ICollection<HoganField> HoganField { get; set; }
        public virtual ICollection<HoganField> HoganField1 { get; set; }
        public virtual ICollection<PracticeReport> PracticeReport { get; set; }
        public virtual ICollection<PracticeReport> PracticeReport1 { get; set; }
        public virtual ICollection<PracticeReport> PracticeReport2 { get; set; }
        public virtual ICollection<PracticeReport> PracticeReport3 { get; set; }
        public virtual ICollection<PracticeText> PracticeText { get; set; }
        public virtual ICollection<ResxValue> ResxValues { get; set; }
    }
}
