//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.ProgramSites = new HashSet<ProgramSite>();
            this.SiteUsers = new HashSet<SiteUser>();
            this.OESSetup = new HashSet<OESSetup>();
        }
    
        public int Id { get; set; }
        public string SiteName { get; set; }
        public string FriendlyName { get; set; }
        public string BrandingColor { get; set; }
        public byte[] BrandingLogo { get; set; }
        public string BrandingLogoMimeType { get; set; }
        public byte[] BrandingBackground { get; set; }
        public string BrandingBackgroundMimeType { get; set; }
        public Nullable<int> OrganizationId { get; set; }
    
        public virtual ICollection<ProgramSite> ProgramSites { get; set; }
        public virtual ICollection<SiteUser> SiteUsers { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<OESSetup> OESSetup { get; set; }
    }
}
