//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCanididateHospitalsByProgram
    {
        public int CandidateId { get; set; }
        public int ProgramHospitalId { get; set; }
        public string HospitalName { get; set; }
        public int HospitalId { get; set; }
    }
}
