//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZCOExportTemplateMap
    {
        public int Id { get; set; }
        public int ZCOExportTemplateId { get; set; }
        public int ZCOExportMapId { get; set; }
    
        public virtual ZCOExportMap ZCOExportMap { get; set; }
        public virtual ZCOExportTemplate ZCOExportTemplate { get; set; }
    }
}
