//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Core.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZCOExportMap
    {
        public ZCOExportMap()
        {
            this.ZCOExportTemplateMaps = new HashSet<ZCOExportTemplateMap>();
        }
    
        public int Id { get; set; }
        public string HoganColName { get; set; }
        public string ZCOColName { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual ICollection<ZCOExportTemplateMap> ZCOExportTemplateMaps { get; set; }
    }
}
